[package]
name = "dys"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[features]
default = ["dock"]
dock = []

[dependencies]
clap = { version = "3.2.25", features = ["derive"] }
gtk = { version = "0.14.0", features = ["v3_20"] }
gdk = "0.14.0"
gio = "0.14.0"
glib = "0.14.2"

gio-sys = "0.14.0"

